language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: "3.7-dev"
    - os: osx
      language: generic

addons:
  apt:
    packages:
      - mediainfo
      - poppler-utils

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mediainfo poppler; fi

install: "pip install pygments"

script: ./test.sh
