language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: "3.7-dev"
    - os: osx
      language: generic

addons:
  apt:
    packages:
      - mediainfo
      - poppler-utils

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mediainfo poppler; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m ensurepip --user; fi

install: 
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pip install pygments --user; else python -m pip install pygments; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$HOME/Library/Python/2.7/bin/:$PATH; fi

script: ./test.sh
